Stripe account plugin
webriq-pagebuilder/studio-template-default pull request #44
Opened 2021-08-06 11:22 UTC by ronix-webriq

Plugin Implemented,
variant-x override under pricing section
after account created, you can select on pricing section dropdown for the stripe account.

2021-08-09 01:15 UTC, mamfi-0221 commented on package.json
> +    "@webriq-pagebuilder/sanity-plugin-schema-default": "^0.0.6",
`@webriq-pagebuilder/sanity-plugin-schema-default` package version is 0.1.0 as per most recent update.

2021-08-09 02:15 UTC, mamfi-0221 commented on plugins/webriq-payments/WebriQPayments.js
> +  const ops = useDocumentOperation('stripe-account', 'array')
If you agree,  I think it would be best to change this variable name into something that will help identify what this is for.

2021-08-09 02:21 UTC, mamfi-0221 commented on plugins/webriq-payments/WebriQPayments.js
> +  const {useCallback, useState} = React
These built-in React hooks can either be defined in line 1 or use the "React" default export name.

2021-08-09 02:31 UTC, mamfi-0221 commented on plugins/webriq-payments/components/viewAccounts.js
> +import React, {useRef, } from 'react'
Is the `useRef` React hook being used?

2021-08-09 02:52 UTC, mamfi-0221 requested changes
Added my comments on code for review. 

In addition:
1. **_theme-manager_** code changes are not part of stripe-checkout and should be in a separate PR.
2. Kindly rename `plugins/webriq-payments/WebriQPayments.js` to either `dashboard` or what may fit its purpose since file currently is in the webriq-payments folder and its not clear what this is for unless we check the code structure.
3. Shouldn't all files added to `schemas/custom/` be added to the sanity-packages instead or is this change would not be applied to all?

Thank you!

2021-09-17 03:10 UTC, webriq commented
Closing as we migrated this to API version.

2021-09-17 03:10 UTC, closed without merging