Implement schema-blog plugin
webriq-pagebuilder/studio-template-default pull request #54
Opened 2021-09-27 07:31 UTC by mamfi-0221

Add schema-blog to studio to enable creating posts, categories and authors linked as reference to the blog section.

2021-09-30 13:41 UTC, webriq approved these changes

2021-09-30 13:58 UTC, webriq requested changes
Please merge latest `develop` to your branch.

2021-09-30 13:59 UTC, webriq requested changes
Please merge latest `develop` to your branch.

2021-10-01 02:30 UTC, mamfi-0221 commented
> Please merge latest `develop` to your branch.

Merged develop to branch and resolved conflicts. Thanks!

2021-10-01 08:20 UTC, webriq approved these changes

2021-10-01 09:53 UTC, webriq approved these changes

2021-10-01 09:53 UTC, merged